name: Fetch, Resolve, and Geolocate IPs/Domains

on:
  schedule:
    # 每3小时运行一次 (0, 3, 6, 9, 12, 15, 18, 21点 UTC)
    - cron: '0 */3 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 允许工作流写入仓库

jobs:
  fetch_and_process:
    runs-on: ubuntu-latest
    env:
      IPDATA_API_KEY: ${{ secrets.IPDATA_API_KEY }} # 从 GitHub Secrets 获取 API Key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (jq, dig)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq dnsutils # dnsutils 包含 dig

      - name: Check for IPDATA_API_KEY
        run: |
          if [ -z "${IPDATA_API_KEY}" ]; then
            echo "Error: IPDATA_API_KEY secret is not set. Please add it to your repository secrets."
            exit 1
          fi
          echo "IPDATA_API_KEY found."

      - name: Fetch targets (IPs/Domains) from sources
        id: fetch_targets
        run: |
          echo "Fetching targets from source 1 (ymyuuu)..."
          curl -sSL "https://raw.githubusercontent.com/ymyuuu/IPDB/refs/heads/main/BestCF/bestcfv4.txt" > targets_source1.txt
          echo "Fetching targets from source 2 (ethgan)..."
          curl -sSL "https://raw.githubusercontent.com/ethgan/yxip/refs/heads/main/ip.txt" > targets_source2.txt
          echo "Fetching targets from source 3 (mefele)..."
          curl -sSL "https://raw.githubusercontent.com/mefele/test/refs/heads/main/1.txt" > targets_source3.txt
          
          echo "Combining and unique targets from 3 sources..."
          # cat所有源，然后sort -u去重，不过滤IP，因为现在也可能是域名
          cat targets_source1.txt targets_source2.txt targets_source3.txt | sed '/^\s*$/d' | sort -u > all_unique_targets.txt
          
          echo "Total unique targets found: $(wc -l < all_unique_targets.txt)"
          if [ ! -s all_unique_targets.txt ]; then
            echo "No targets found to process."
            echo "NO_TARGETS=true" >> $GITHUB_ENV
          else
            echo "NO_TARGETS=false" >> $GITHUB_ENV
          fi

      - name: Resolve domains and geolocate (using ipdata.co)
        if: env.NO_TARGETS == 'false' && env.IPDATA_API_KEY != ''
        run: |
          echo "Starting domain resolution and geolocation process with ipdata.co..."
          OUTPUT_FILE="geolocated_targets.txt"
          ERROR_LOG_FILE="geolocation_errors.txt"
          > "$OUTPUT_FILE" 
          > "$ERROR_LOG_FILE"

          get_chinese_country_name() {
            local code="$1"
            local english_name="$2"
            case "$code" in
              "US") echo "美国";; "CA") echo "加拿大";; "CN") echo "中国";;
              "HK") echo "中国香港";; "TW") echo "中国台湾";; "JP") echo "日本";;
              "KR") echo "韩国";; "SG") echo "新加坡";; "GB") echo "英国";;
              "DE") echo "德国";; "FR") echo "法国";; "AU") echo "澳大利亚";;
              "NL") echo "荷兰";; "RU") echo "俄罗斯";; "IN") echo "印度";;
              "BR") echo "巴西";; "VN") echo "越南";; "MY") echo "马来西亚";;
              "TH") echo "泰国";; "ID") echo "印度尼西亚";;
              *) echo "$english_name";;
            esac
          }
          export -f get_chinese_country_name

          is_ip_address() {
            local target="$1"
            if [[ "$target" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
              return 0
            else
              return 1
            fi
          }

          while IFS= read -r target_line; do
            target_line=$(echo "$target_line" | tr -d '\r' | xargs) # Clean input
            if [ -z "$target_line" ]; then
              continue
            fi

            original_target="$target_line"
            ip_to_query=""

            if is_ip_address "$target_line"; then
              ip_to_query="$target_line"
              echo "Processing IP: $ip_to_query (from input: $original_target)"
            else
              echo "Processing Domain: $target_line, attempting to resolve..."
              # 改进的dig命令，优先获取A记录的IP，并过滤确保是IP格式
              resolved_ip=$(dig +short A "$target_line" | grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -n 1)
              
              if [ -z "$resolved_ip" ]; then
                # 如果A记录没有直接IP，尝试解析AAAA后获取IP (更复杂，暂时简化)
                # 或者直接标记为解析失败
                echo "Error: Could not resolve domain $target_line to a valid IP" >> "$ERROR_LOG_FILE"
                echo "$original_target#DOMAIN_RESOLUTION_FAILED" >> "$OUTPUT_FILE"
                sleep 0.5 
                continue
              else
                ip_to_query="$resolved_ip"
                echo "Domain $target_line resolved to IP: $ip_to_query"
              fi
            fi
            
            api_url="https://api.ipdata.co/${ip_to_query}?api-key=${IPDATA_API_KEY}&fields=ip,country_name,country_code"
            response=$(curl -sSL "$api_url")
            
            # 检查响应中是否存在 country_code 并且不为 null
            countryCode=$(echo "$response" | jq -r .country_code)
            countryNameEn=$(echo "$response" | jq -r .country_name)
            queryIp=$(echo "$response" | jq -r .ip) # API确认的IP

            if [ "$countryCode" != "null" ] && [ -n "$countryCode" ] && [ "$countryNameEn" != "null" ] && [ -n "$countryNameEn" ]; then
              chineseCountryName=$(get_chinese_country_name "$countryCode" "$countryNameEn")
              echo "$original_target#${countryCode}${chineseCountryName}" >> "$OUTPUT_FILE"
            else
              # 如果 country_code 或 country_name 为 null，但API请求本身可能没报错 (只是没数据)
              # 检查是否有明确的API错误消息
              apiErrorMessage=$(echo "$response" | jq -r '.message // ""')
              if [ -n "$apiErrorMessage" ]; then
                 # API返回了明确的错误消息（例如 "not a valid IPv4 or IPv6 address"）
                echo "Error geolocating (API Msg: $apiErrorMessage) for IP $ip_to_query (from target $original_target). API Response: $response" >> "$ERROR_LOG_FILE"
                echo "$original_target#${ip_to_query}#API_ERROR_OR_INVALID_IP" >> "$OUTPUT_FILE"
              else
                # API没有明确错误，但国家信息为null
                echo "Warning: Geolocation data (country_code/name is null) for IP $ip_to_query (from target $original_target). API Response: $response" >> "$ERROR_LOG_FILE"
                echo "$original_target#${queryIp}#GEO_DATA_NULL" >> "$OUTPUT_FILE"
              fi
            fi
            
            sleep 2 
          done < all_unique_targets.txt

          echo "Geolocation process finished. Results in $OUTPUT_FILE"
          if [ -s "$ERROR_LOG_FILE" ]; then
            echo "Some errors occurred during geolocation. Check $ERROR_LOG_FILE for details."
          fi
      - name: Commit and push if changes
        if: env.NO_TARGETS == 'false' && env.IPDATA_API_KEY != ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add geolocated_targets.txt geolocation_errors.txt
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update geolocated IP/Domain list (ipdata.co) ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
            echo "Changes committed and pushed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
