name: Collect and Merge Cloudflare IPs

on:
  schedule:
    - cron: '0 0,12 * * *'  # 每天 00:00 和 12:00 UTC 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch from Source 1 (cf.090227.xyz)
        run: |
          echo "Fetching from source 1..."
          curl -s https://cf.090227.xyz/ | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' > 1.txt
          echo "Source 1 done. IPs:"
          cat 1.txt

      - name: Fetch from Source 2 (ip.164746.xyz)
        run: |
          echo "Fetching from source 2..."
          curl -s https://ip.164746.xyz | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' > 2.txt
          echo "Source 2 done. IPs:"
          cat 2.txt

      - name: Fetch from Source 3 (HostMonit JSON API)
        run: |
          echo "Fetching from HostMonit JSON API..."
          python3 -c "
import requests
url = 'https://api.hostmonit.com/get_optimization_ip?type=1'
res = requests.get(url)
ips = res.json().get('info', [])
with open('3.txt', 'w') as f:
    for ip in ips:
        f.write(ip['ip'] + '\\n')
"
          echo "Source 3 done. IPs:"
          cat 3.txt

      - name: Merge and deduplicate all IPs
        run: |
          echo "Merging and deduplicating..."
          cat 1.txt 2.txt 3.txt | sort | uniq > all.txt
          echo "All unique IPs:"
          cat all.txt

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add 1.txt 2.txt 3.txt all.txt
          git diff --cached --quiet || git commit -m "Update IP list at $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push || echo "Nothing to push"
